Feat: Added clean register scene
iasvladimir/be-careful pull request #5
Opened 2020-08-24 18:41 UTC by CharlsIA03

Register Scene on clean architecture

2020-08-24 23:06 UTC, iasvladimir requested changes

2020-08-24 23:06 UTC, iasvladimir commented on BeCareful/Modules/Register/Register scene/RegisterModels.swift
> +  }
Considero que podríamos eliminar las structs _Response_ y _ViewModel_. No es precisamente necesario declararlas si no van a poseer implementación, no se desobedece algún guideline de Clean Swift.

2020-08-25 15:21 UTC, CharlsIA03 commented on BeCareful/Modules/Register/Register scene/RegisterModels.swift
> +  }
Se han eliminado las "structs" de Response y ViewModel

2020-08-25 19:26 UTC, iasvladimir approved these changes

2020-08-25 19:26 UTC, iasvladimir commented on BeCareful/Modules/Register/Register scene/RegisterModels.swift
> +  }
Muy bien, gracias, Charly.

2020-08-25 21:48 UTC, merged